# 这个本地使用无需发布，配置都不会打包
server:
  tomcat:
    accesslog:
      enabled: false
    basedir: ""
---
# DB
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seezoon?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=60000&rewriteBatchedStatements=true
    username: root
    password:
---